events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent';
    access_log /var/log/nginx/access.log main;
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=30r/m;

    upstream api {
        least_conn;  
        server api:3000;
    }

    server {
        listen 80;
        server_name rysuv.com;
        return 301 https://$host$request_uri;  
    }

    server {
        listen 443 ssl;
        server_name localhost rysuv.com;
        ssl_certificate     /etc/nginx/cert.pem;
        ssl_certificate_key /etc/nginx/key.pem;

        location /api/ {
            client_max_body_size 50M;
            limit_req zone=mylimit burst=5 nodelay;
            limit_req_status 429;
            proxy_pass https://api/;
            proxy_ssl_verify off;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}