SET IDENTITY_INSERT [dbo].[Acceso] ON
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (1, N'Administrador', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 1, N'e1cf545a794ba3ac7665035488de6e2a:46274e05fc46c8004d6f6bdaf5c31bdb', N'aadc8665b00328f2c8084afdff53ff15:4a01c7aa95d46e4eac4f567287510803','6f07772e8a62d6414718b7a02b863b50:800390d94ac50a56840d7b34361f7b1d', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (2, N'Guadalupe', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 4, N'b191bf7cd8fe0d4a6e701a356f744bbc:f958558cca7df40596700234667fa591', N'c7ad82ecd1a8595a3d4f1b847a226bbb:741e1b9a20d54b5abe21412c5a4d9dc7', N'07810776cbde3e9f9f03c7c7f164865d:2811f7e5219d7d0e5f86c611058bac04', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (3, N'Alvaro', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 1, N'a104eb3d7aae1d287447fa923eb35c2a:1eb930d8d0ff866e3eac5f4993f8f39e', N'3c5cb67ba6ed16f275035ec99177e02d:e042885a27872f748fe83f930a0c8862', N'06e49e9490ec843c92e3870cbb8d9965:eeb83381240ec6d6703cf292d8db3b89', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (4, N'Karla', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 2, N'5ef25c265bb9adbc1dd26d5eca38d745:1c39a398c417ddf716098229041d3342', N'bbe3c4f627ecfc820566cc71c31532ae:55a09a68f77c14bdcee75a8dd68a5ac6', N'a610ea0f5f13d4345f5514bed33ae416:0671487949cf96205037e11ab94b8eed', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (5, N'Fernanda', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 2, N'c6400c94ed4f35e4f7386f5f53485d97:e48b52ead35c10173d7516ecce8619a6', N'fdb3ad945fb7333c67ea9d9aa46ee370:ca4b37ea12ff118b3f1a36814b4f22d1', N'ed596e96c6f9914852fd5375764308fc:918ebe0c5455cbbf6c77902923e33503', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (6, N'Emmanuel', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 3, N'2d6181c3277ea7fd0671391b32676ce4:22c1ddcefb8d6872e827e5272de91d6b67c93096180f9a8046fc3d1b5cceca27', N'12ae3e61e890fb9f89773543f8c13eb4:f34e109e2c4326458c6aa2dfcd533aae', N'1d22e6cb1bb68f112fd1ed1465dac566:c96453a43215bec64f53731e7f16c9fd', 1)
INSERT [dbo].[Acceso] ([idAcceso], [usuario], [contrasenia], [FKIdTipoAcceso], [nombre], [primerApellido], [segundoApellido], [estado]) VALUES (7, N'Daniel', N'$2b$05$zsPkVw0/ST6PLg5RXO9AuOentp1cHwfquFNrtO6VLmBGnsIlvcuea', 3, N'a992d9d8f334ad7ccb3c53573e170e3d:a0fa77eb04f0ba269d89ced3b517b0dc', N'd4f91a227c59b4b7b2afa619200c7f59:887be16df78db6f5f293d9960ca8e163', N'a295486f916d6f13140e0476dd6dc76a:d5318388af3a02ea416412b41e4ff4f9', 1)
SET IDENTITY_INSERT [dbo].[Acceso] OFF
GO
SET IDENTITY_INSERT [dbo].[ClasificacionCedula] ON 
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (1, 1, N'Asistente Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (2, 2, N'Asistente Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (3, 3, N'Asistente Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (4, 6, N'Asistente Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (5, 7, N'Asistente Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (6, 8, N'Asistente Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (7, 10, N'Asistente Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (8, 11, N'Asistente Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (9, 12, N'Apoyo Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (10, 13, N'Apoyo Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (11, 14, N'Apoyo Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (12, 15, N'Apoyo Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (13, 16, N'Apoyo TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (14, 19, N'Apoyo Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (15, 21, N'Apoyo Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (16, 22, N'Apoyo Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (17, 23, N'Enlace Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (18, 24, N'Enlace Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (19, 25, N'Enlace Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (20, 26, N'Enlace Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (21, 27, N'Enlace TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (22, 28, N'Enlace Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (23, 31, N'Enlace Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (24, 32, N'Enlace Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (25, 34, N'Analista Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (26, 35, N'Analista Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (27, 36, N'Analista Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (28, 37, N'Analista Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (29, 38, N'Analista TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (30, 39, N'Analista Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (31, 40, N'Analista Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (32, 42, N'Analista Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (33, 43, N'Analista Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (34, 44, N'Analista Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (35, 45, N'Gestor Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (36, 47, N'Gestor Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (37, 48, N'Gestor Normativo Juridico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (38, 49, N'Gestor TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (39, 50, N'Gestor Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (40, 51, N'Gestor Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (41, 52, N'Gestor Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (42, 53, N'Gestor Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (43, 54, N'Gestor Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (44, 55, N'Gestor Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (45, 56, N'Especialista Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (46, 57, N'Especialista Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (47, 58, N'Especialista Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (48, 59, N'Especialista Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (49, 60, N'Especialista TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (50, 61, N'Especialista Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (51, 62, N'Especialista Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (52, 63, N'Especialista Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (53, 64, N'Especialista Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (54, 65, N'Especialista Comunicación Y Edición')
SET IDENTITY_INSERT [dbo].[ClasificacionCedula] OFF
GO
SET IDENTITY_INSERT [dbo].[Competencia] ON 
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (1, N'Comunicación')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (2, N'Trabajo en equipo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (3, N'Orientación al servicio')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (4, N'Sensibilidad a lineamientos')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (5, N'Planeación y organización')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (6, N'Análisis de problemas')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (7, N'Enfoque a resultados')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (8, N'Control de actividades')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (9, N'Enfoque a la calidad')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (10, N'Relaciones interpersonales')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (11, N'Liderazgo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (12, N'Toma de decisiones')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (13, N'Dinamismo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (14, N'Innovación')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (15, N'Pensamiento estratégico')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (16, N'Negociación')
SET IDENTITY_INSERT [dbo].[Competencia] OFF
GO