USE [SistemaServicioSocial]
GO

SET IDENTITY_INSERT [dbo].[ClasificacionCedula] ON 
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (1, 1, N'Asistente Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (2, 2, N'Asistente Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (3, 3, N'Asistente Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (4, 6, N'Asistente Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (5, 7, N'Asistente Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (6, 8, N'Asistente Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (7, 10, N'Asistente Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (8, 11, N'Asistente Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (9, 12, N'Apoyo Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (10, 13, N'Apoyo Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (11, 14, N'Apoyo Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (12, 15, N'Apoyo Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (13, 16, N'Apoyo TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (14, 19, N'Apoyo Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (15, 21, N'Apoyo Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (16, 22, N'Apoyo Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (17, 23, N'Enlace Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (18, 24, N'Enlace Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (19, 25, N'Enlace Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (20, 26, N'Enlace Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (21, 27, N'Enlace TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (22, 28, N'Enlace Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (23, 31, N'Enlace Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (24, 32, N'Enlace Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (25, 34, N'Analista Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (26, 35, N'Analista Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (27, 36, N'Analista Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (28, 37, N'Analista Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (29, 38, N'Analista TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (30, 39, N'Analista Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (31, 40, N'Analista Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (32, 42, N'Analista Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (33, 43, N'Analista Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (34, 44, N'Analista Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (35, 45, N'Gestor Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (36, 47, N'Gestor Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (37, 48, N'Gestor Normativo Juridico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (38, 49, N'Gestor TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (39, 50, N'Gestor Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (40, 51, N'Gestor Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (41, 52, N'Gestor Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (42, 53, N'Gestor Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (43, 54, N'Gestor Comunicación Y Edición')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (44, 55, N'Gestor Operativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (45, 56, N'Especialista Académico Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (46, 57, N'Especialista Administrativo Académico')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (47, 58, N'Especialista Administrativo')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (48, 59, N'Especialista Normativo Jurídico Legal')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (49, 60, N'Especialista TICs')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (50, 61, N'Especialista Salud')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (51, 62, N'Especialista Cultura')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (52, 63, N'Especialista Deporte')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (53, 64, N'Especialista Presupuestal Contable')
INSERT [dbo].[ClasificacionCedula] ([idClasificacionCedulas], [numCedula], [nombre]) VALUES (54, 65, N'Especialista Comunicación Y Edición')
SET IDENTITY_INSERT [dbo].[ClasificacionCedula] OFF
GO

SET IDENTITY_INSERT [dbo].[Competencia] ON 
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (1, N'Comunicación')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (2, N'Trabajo en equipo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (3, N'Orientación al servicio')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (4, N'Sensibilidad a lineamientos')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (5, N'Planeación y organización')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (6, N'Análisis de problemas')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (7, N'Enfoque a resultados')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (8, N'Control de actividades')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (9, N'Enfoque a la calidad')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (10, N'Relaciones interpersonales')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (11, N'Liderazgo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (12, N'Toma de decisiones')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (13, N'Dinamismo')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (14, N'Innovación')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (15, N'Pensamiento estratégico')
INSERT [dbo].[Competencia] ([idCompetencia], [nombre]) VALUES (16, N'Negociación')
SET IDENTITY_INSERT [dbo].[Competencia] OFF
GO